
Map languagesNumbersMap = {
    'vietnamese': 8,
    'uzbek': 15,
    'ukranian': 34,
    'turkish': 49,
    'thai': 8,
    'tatar': 5,
    'swedish': 49,
    'swahili': 7,
    'spanish': 49,
    'slovenian': 10,
    'slovak': 11,
    'serbian': 49,
    'russian': 49,
    'romanian': 49,
    'punjabi': 6,
    'portuguese': 49,
    'polish': 49,
    'persian': 49,
    'norwegian': 25,
    'neapolitan': 11,
    'malay': 5,
    'macedonian': 11,
    'lithuanian': 9,
    'latvian': 14,
    'latin': 14,
    'kurdish-sorani': 11,
    'kurdish': 18,
    'korean': 49,
    'kazakh': 11,
    'italian': 49,
    'indonesian': 15,
    'icelandic': 9,
    'hungarian': 45,
    'hindi': 18,
    'hebrew': 49,
    'greek': 49,
    'german': 49,
    'french': 49,
    'finnish': 49,
    'filipino': 11,
    'estonian': 14,
    'english': 49,
    'dutch': 23,
    'danish': 33,
    'czech': 28,
    'croatian': 49,
    'catalan': 25,
    'cape-verdean': 11,
    'bulgarian': 49,
    'bosnian': 27,
    'belarusian': 6,
    'azerbaijani': 16,
    'armenian': 7,
    'arabic': 49,
    'albanian': 37
};

Map convertedLanguages = {
     'vt': 'vietnamese',
    'uz':'uzbek',
    'ua':'ukranian',
    'tr':'turkish',
    'th':'thai',
    'tt':'tatar',
    'se':'swedish',
    'sw':'swahili',
    'es': 'spanish',
    'si':'slovenian',
    'sk':'slovak',
    'rs':'serbian',
    'ru': 'russian',
    'ro':'romanian',
    'pj':'punjabi',
    'pt':'portuguese',
    'pl':'polish',
    'ir':'persian',
    'no':'norwegian',
    'np':'neapolitan',
    'my':'malay',
    'mk':'macedonian',
    'lt':'lithuanian',
    'lv':'latvian',
    'la':'latin',
    'kus':'kurdish-sorani',
    'kuk':'kurdish',
    'kr':'korean',
    'kz':'kazakh',
    'it':'italian',
    'id':'indonesian',
    'is':'icelandic',
    'hu':'hungarian',
    'in':'hindi',
    'il':'hebrew',
    'gr':'greek',
    'de':'german',
    'fr':'french',
    'fi':'finnish',
    'ph':'filipino',
    'ee':'estonian',
    'us':'english',
    'nl':'dutch',
    'dk':'danish',
    'cz':'czech',
    'hr':'croatian',
    'ct':'catalan',
    'cv':'cape-verdean',
    'bg':'bulgarian',
    'ba':'bosnian',
    'by':'belarusian',
    'az':'azerbaijani',
    'am':'armenian',
    'ar': 'arabic',
    'al': 'albanian',
};


Map languageCodes = {
  'albanian': 'mUCQsV250DdfSRhw7s5C',
  'arabic': 'ewiMHGey21gxtqimljBb',
  'armenian': 'vTAHrR3OWDCcvJUCMqas',
  'azerbaijani': 'a5KI0gztRUxRBod9P6JM',
  'belarusian': 'JSIFXwIgY9OPAJQGmA7G',
  'bosnian': 'E4MoUsOFb7SCGd7a6wic',
  'bulgarian': 'hDteaMoPW5lPMAWrhzr4',
  'cape verdean': 'IUTGrMvl7To1JpWaLiRk',
  'catalan': 'j5nhc4sqCwLmv0gNQDxA',
  'croatian': 'v4Q29cPWVws0wKyXTWN1',
  'czech': 'FDCOWoivf9M9UuH1sRTu',
  'danish': 'q26yd4MXh4EaWbHH0HPk',
  'dutch': 'ukLGyQzteFf9k68xWW5o',
  'english': 'mZRax7KkRWGR5F2s90HY',
  'estonian': 'vUePyBdReFxN5eCFWaCz',
  'filipino': '0eS7uZGmPma8hIvnuLnR',
  'finnish': '34Uc1Iu984P5GUFHRiOy',
  'french': 'KZ6Fe9NDHt7WdRypBGs7',
  'german': 'wiFTgiTPAcWO73KuPMnI',
  'greek': 'wl7YQ2g5XMzIQja98mv2',
  'hebrew': 'zZhVZ42bBUXJSYYaifvc',
  'hindi': 'HeizLxi8rzaB8swLunir',
  'hungarian': 'bqx1FwLGarw3Uz7uYU7E',
  'icelandic': 'i7UT5atrEKH5mk3Ld1hN',
  'indonesian': 'Er6hngcaxRyDEwlYmlGR',
  'italian': 'MVIdoxkJSE1JbEDxxaka',
  'kazakh': 'LpvGsosE0w9tuLY7JzW1',
  'korean': '6mNHD0xYXEPQNcr2i5wO',
  'kurdish': 'aOIBRpRb89089yipubvm',
  'kurdish sorani': 'DlNg5RCMQLWBCyBH42e2',
  'latin': 'XlRaH4WPVP20UsoHnqMn',
  'latvian': 'G8EyXAY7VusnsHz84jVJ',
  'lithuanian': '7072GvW3jU4XJG0NjDYe',
  'macedonian': '5NedyuAVK1cijDVKA905',
  'malay': '6Rp80EkCubx978AKaoLX',
  'neapolitan': '2O4tZyB3ENfDOHautnY2',
  'norwegian': 'L8ioBAmIcBnW9kSCNv8q',
  'persian': 'ZpPEVcUZr27GdmOkql1Z',
  'polish': 'XA7xjJAfzK8FRewNdNhw',
  'portuguese': 'PC80OuCyHMbN6qgXbCr5',
  'punjabi': 'aC6kXH0NzF4ucE4YQWAJ',
  'romanian': 'QXdfJrLKNQE6N8oCl7lY',
  'russian': 'koTjC30u0lxHgA312Pc3',
  'serbian': 'n7o6tbHJJofzCM8MJ3ZN',
  'slovak': '8njrc1arMMnvBZERLLMQ',
  'slovenian': 'xyOx9BDe4kT6oOemWZwG',
  'spanish': 'brlOi12QkiLNJX2ACJDQ',
  'swahili': '7s2Znw0EiCMERF6X5t52',
  'swedish': '7zgO1WHmiKDQCMGVN0sg',
  'tatar': 'kTgBuhFZmdJmSDMM5DBA',
  'thai': 'Amu5XFDjxwJezPCS8YoL',
  'turkish': 'l3KIkjmAyO8hBtdvytKg',
  'ukrainian': 'p9zySWblDAvhm2vgXkEI',
  'uzbek': 'm4lNCveFImIbTHRAcBcB',
  'vietnamese': 'txBvNFdIk2dhoxdDy8YF',
};