var privacyList = [
  "We may collect the following information about you voluntarily by setting up an account or making changes in profile settings:",
  "•	Email",
  "•	Username",
  "We may collect the following information about you automatically through your use of the app:",
  "•	Streak Score",
  "•	Stars Earned",
  "•	Languages you have studied",
  "•	Information on the words you have studied like the word, the translated word, and your progress with learning that word",
  "•	Information on the songs you have studied like the song title, the creator, the Youtube URL, the unique words in the lyrics, your progress in learning the song, and which language’s collection to which the song belongs",
  "•	Progress in the courses",
  "We may use your personal information to do the following:",
  "•	Operate and improve the app",
  "•	Establish and maintain your account",
  "•	Communicate with you about the app by sending announcements and updates by email or push notifications",
  "•	Aid our response to your requests, questions, and feedback",
  "•	Provide technical support and maintenance for the app.",
  "We share no data with third parties.",
  "We store data indefinitely and may delete it at any time.",
  "We provide a means of revoking consent to our data use. If you wish to revoke consent, send an email to the following email address: musiclanguagelearningapp@gmail.com with the subject “Delete My Account.” The email must be sent from the same address your account is connected to."
];
